---

- src: https://github.com/companieshouse/ansible-role-mounted-volume
  name: mounted-volume
  version: "1.0.3"

- src: https://github.com/geerlingguy/ansible-role-repo-epel
  name: epel
  version: "1.3.0"

- src: https://github.com/geerlingguy/ansible-role-pip
  name: pip
  version: "2.0.0"
